// types
export const PRIMARY = 'primary'
export const SECONDARY = 'secondary'
export const SUCCESS = 'success'
export const DANGER = 'danger'
export const WARNING = 'warning'
export const INFO = 'info'
export const LIGHT = 'light'
export const DARK = 'dark'
export const LINK = 'link'

// size
export const LARGE = 'large'
export const SMALL = 'small'

// inline
export const GROUP = 'group'
export const CLOSE = 'close'
export const ACTIVE = 'active'
export const DISABLED = 'disabled'
export const VERTICAL = 'vertical'
export const TOP = 'top'
export const BOTTOM = 'bottom'
export const OVERLAY = 'overlay'
export const NONE = 'd-none'
export const MD_BLOCK = 'd-md-block'
export const ICON = 'icon'
export const PREV = 'prev'
export const NEXT = 'next'

// components
export const ALERT = 'alert'
export const ALERT_LINK = 'alert-link'
export const ALERT_HEADING = 'alert-heading'
export const ALERT_DISMISSIBLE = 'alert-dismissible'

export const BADGE = 'badge'
export const BADGE_TOP = 'badge-top'
export const BADGE_WRAP = 'badge-wrap'
export const BADGE_PILL = 'badge-pill'

export const BREADCRUMB = 'breadcrumb'
export const BREADCRUMB_ITEM = 'breadcrumb-item'

export const BUTTON = 'btn'
export const BUTTON_BLOCK = 'btn-block'

export const BUTTON_TOOLBAR = 'btn-toolbar'

export const CARD = 'card'
export const CARD_INVERSE = 'text-white'
export const CARD_ALIGN_CENTER = 'text-center'
export const CARD_ALIGN_RIGHT = 'text-right'
export const CARD_BG = 'bg'
export const CARD_BORDER = 'border'
export const CARD_BODY = 'card-body'
export const CARD_IMG = 'card-img'
export const CARD_LINK = 'card-link'
export const CARD_TEXT = 'card-text'
export const CARD_TITLE = 'card-title'
export const CARD_SUBTITLE = 'card-subtitle'
export const CARD_HEADER = 'card-header'
export const CARD_FOOTER = 'card-footer'
export const CARD_GROUP = 'card-group'
export const CARD_DECK = 'card-deck'
export const CARD_COLUMNS = 'card-columns'

export const CAROUSEL = 'carousel'
export const CAROUSEL_VIEW = 'carousel-view'
export const CAROUSEL_ITEM = 'carousel-track-item'
export const CAROUSEL_TRACK = 'carousel-track'
export const CAROUSEL_CAPTION = 'carousel-caption'
export const CAROUSEL_INDICATORS = 'carousel-indicators'
export const CAROUSEL_CONTROL_PREV = 'carousel-control-prev'
export const CAROUSEL_CONTROL_NEXT = 'carousel-control-next'

export const COLLAPSE = 'collapse'
