// types
export const PRIMARY = 'primary'
export const SECONDARY = 'secondary'
export const SUCCESS = 'success'
export const DANGER = 'danger'
export const WARNING = 'warning'
export const INFO = 'info'
export const LIGHT = 'light'
export const DARK = 'dark'
export const LINK = 'link'

// size
export const LARGE = 'large'
export const SMALL = 'small'

// inline
export const GROUP = 'group'
export const CLOSE = 'close'
export const ACTIVE = 'active'
export const DISABLED = 'disabled'
export const VERTICAL = 'vertical'
export const TOP = 'top'
export const BOTTOM = 'bottom'
export const OVERLAY = 'overlay'
export const NONE = 'd-none'
export const MD_BLOCK = 'd-md-block'
export const ICON = 'icon'
export const PREV = 'prev'
export const NEXT = 'next'
export const MENU = 'xbrick-menu'
export const ROW = 'row'
export const SR_ONLY = 'sr-only'

// components
export const ALERT = 'alert'
export const ALERT_LINK = 'alert-link'
export const ALERT_HEADING = 'alert-heading'
export const ALERT_DISMISSIBLE = 'alert-dismissible'

export const BADGE = 'badge'
export const BADGE_TOP = 'badge-top'
export const BADGE_WRAP = 'badge-wrap'
export const BADGE_PILL = 'badge-pill'

export const BREADCRUMB = 'breadcrumb'
export const BREADCRUMB_ITEM = 'breadcrumb-item'

export const BUTTON = 'btn'
export const BUTTON_BLOCK = 'btn-block'
export const BUTTON_GROUP = 'btn-group'
export const BUTTON_TOOLBAR = 'btn-toolbar'

export const CARD = 'card'
export const CARD_INVERSE = 'text-white'
export const CARD_ALIGN_CENTER = 'text-center'
export const CARD_ALIGN_RIGHT = 'text-right'
export const CARD_BG = 'bg'
export const CARD_BORDER = 'border'
export const CARD_BODY = 'card-body'
export const CARD_IMG = 'card-img'
export const CARD_LINK = 'card-link'
export const CARD_TEXT = 'card-text'
export const CARD_TITLE = 'card-title'
export const CARD_SUBTITLE = 'card-subtitle'
export const CARD_HEADER = 'card-header'
export const CARD_FOOTER = 'card-footer'
export const CARD_GROUP = 'card-group'
export const CARD_DECK = 'card-deck'
export const CARD_COLUMNS = 'card-columns'

export const CAROUSEL = 'carousel'
export const CAROUSEL_VIEW = 'carousel-view'
export const CAROUSEL_ITEM = 'carousel-track-item'
export const CAROUSEL_TRACK = 'carousel-track'
export const CAROUSEL_CAPTION = 'carousel-caption'
export const CAROUSEL_INDICATORS = 'carousel-indicators'
export const CAROUSEL_CONTROL_PREV = 'carousel-control-prev'
export const CAROUSEL_CONTROL_NEXT = 'carousel-control-next'

// export const COLLAPSE = 'collapse'
export const DROPDOWN = 'dropdown'
export const DROPDOWN_TOGGLE = 'dropdown-toggle'
export const DROPDOWN_MENU = 'dropdown-menu'
export const DROPDOWN_ITEM = 'dropdown-item'
export const DROPDOWN_DIVIDER = 'dropdown-divider'
export const DROPDOWN_HEADER = 'dropdown-header'
export const DROPUP = 'dropup'
export const DROPRIGHT = 'dropright'
export const DROPLEFT = 'dropleft'

export const FORM_INLINE = 'form-inline'
export const FORM_GROUP = 'form-group'
export const FORM_CHECK = 'form-check'
export const FORM_CHECK_INLINE = 'form-check-inline'
export const FORM_CONTROL = 'form-control'
export const FORM_CHECK_INPUT = 'form-check-input'
export const FORM_CONTROL_PLAINTEXT = 'form-control-plaintext'
export const FORM_CONTROL_FILE = 'form-control-file'

export const FORM_CHECK_LABEL = 'form-check-label'
export const COL_FORM_LABEL = 'col-form-label'

export const CUSTOM_SELECT = 'custom-select'
export const CUSTOM_CONTROL_LABEL = 'custom-control-label'
export const CUSTOM_CONTROL_INPUT = 'custom-control-input'
export const CUSTOM_CONTROL = 'custom-control'
export const CUSTOM_CHECKBOX = 'custom-checkbox'
export const CUSTOM_RADIO = 'custom-radio'

export const INPUT_GROUP = 'input-group'
export const INPUT_GROUP_PREPEND = 'input-group-prepend'
export const INPUT_GROUP_APPEND = 'input-group-append'
export const INPUT_GROUP_TEXT = 'input-group-text'
